lib: [
  "_build/install/default/lib/nsq/META" {"META"}
  "_build/install/default/lib/nsq/opam" {"opam"}
  "_build/install/default/lib/nsq/nsq.cmi"
  "_build/install/default/lib/nsq/nsq.cmx"
  "_build/install/default/lib/nsq/nsq.cmt"
  "_build/install/default/lib/nsq/nsq.cmti"
  "_build/install/default/lib/nsq/nsq.mli"
  "_build/install/default/lib/nsq/nsq.cma"
  "_build/install/default/lib/nsq/nsq.cmxa"
  "_build/install/default/lib/nsq/nsq.a"
  "_build/install/default/lib/nsq/nsq.cmxs"
]
doc: [
  "_build/install/default/doc/nsq/README.md"
  "_build/install/default/doc/nsq/LICENSE"
]
